SELECT count(*) as USERS
FROM user_info
WHERE (YEAR(joined)=2021) AND (age BETWEEN 20 AND 29)

# SELECT COUNT(USER_ID) AS USERS
# FROM USER_INFO
# WHERE (AGE BETWEEN 20 AND 29) AND (YEAR(JOINED)=2021)